version: "3"

networks:
  stormspotter-network:
    driver: "bridge"

services:
  stormspotter-neo4j:
    image: neo4j:latest
    restart: unless-stopped
    networks:
      - stormspotter-network
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/password

  stormspotter-frontend:
    build:
      context: frontend
    depends_on:
      - stormspotter-neo4j
    networks:
      - stormspotter-network
    ports:
      - 9091:9091

  stormspotter-backend:
    tty: true
    build:
      context: backend
    depends_on:
      - stormspotter-neo4j
    networks:
      - stormspotter-network
    ports:
      - 9090:9090
    environment:
      - DOCKER_STORMSPOTTER=1
